version: "3.8"
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  api:
    build: .
    environment:
      STORE: "redis"
      REDIS_ADDR: "redis:6379"
      PORT: "8080"
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  redis-data:
